---
title: "Gecko Diet"
author: "April Lamb, Alex Dornburg, and Dan Warren"
date: "23 September 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Comparing diet in two gecko species 

```{r}
# Set working directory
# setwd("/Users/April/Desktop/More gecko stuff") #Path will need to be updated

# Load packages
library(vegan) # contains all common ordination methods - pca, cca, decorana, nmds
library(MASS)
library(ggplot2)
library(RColorBrewer)
library(ellipse)
library(reshape2)


```

### Diet structure

```{r}
# Read in data
dietsgeckoproportions1 <- read.csv("dietgeckoproportions1.csv", header = TRUE)
colnames(dietsgeckoproportions1)[1] <- "Species"
colnames(dietsgeckoproportions1)[2] <- "Specimen"
dietsgeckoproportions2 <- melt(dietsgeckoproportions1, id.var=c("Species","Specimen"))

cols = topo.colors(19)

# Both species
p2 <- ggplot(dietsgeckoproportions2, aes(x = Specimen, y = value, fill = as.factor(variable))) +
  geom_bar(stat = "identity",width=1) + theme_set(theme_bw(10)) + 
  scale_fill_manual(values = cols, name = "Prey Category", 
                    breaks=c("Diptera", "Lepidoptera","Coleoptera","Archnid_scorp",
                             "Archnid_spider","Other", "Nematodes", "Centipede", 
                             "Isopod", "Hemiptera", "Hymenoptera", "Orthoptera", 
                             "Ephermeroptera", "Gecko_skin", "Blattaria", "Empty", 
                             "Ramphotyphlops", "Gonatodes antillensis", "Phylodactylus"), 
                    labels=c("Diptera", "Lepidoptera","Coleoptera","Archnid scorpion",
                             "Archnid spider","Other", "Nematodes", "Centipede", 
                             "Isopod", "Hemiptera", "Hymenoptera", "Orthoptera", 
                             "Ephermeroptera", "Gecko skin", "Blattaria", "Empty",
                             "Ramphotyphlops", "Gonatodes antillensis", "Phylodactylus"))
p2 + coord_polar() + ylim(-0.5,1.2)

# Write the data into a csv so it can be split in excel into one csv per species
write.csv(dietsgeckoproportions2, file = "gecko.diet.csv")

# Choose files phylodiet and hemidiet, respectively
phylo <- read.csv("phylodiet.csv", header = TRUE)
hemi<-read.csv("hemidiet.csv", header = TRUE)

# Phyllodactylus 
p3 <- ggplot(phylo, aes(x = Specimen, y = value, fill = as.factor(variable))) +
  geom_bar(stat = "identity",width=1) + theme_set(theme_bw(10)) + 
  scale_fill_manual(values = cols, name = "Prey Category", 
                    breaks=c("Diptera", "Lepidoptera","Coleoptera","Archnid_scorp",
                             "Archnid_spider","Other", "Nematodes", "Centipede", 
                             "Isopod", "Hemiptera", "Hymenoptera", "Orthoptera", 
                             "Ephermeroptera", "Gecko_skin", "Blattaria", "Empty", 
                             "Ramphotyphlops", "Gonatodes antillensis", "Phylodactylus"), 
                    labels=c("Diptera", "Lepidoptera","Coleoptera","Archnid scorpion",
                             "Archnid spider","Other", "Nematodes", "Centipede", 
                             "Isopod", "Hemiptera", "Hymenoptera", "Orthoptera", 
                             "Ephermeroptera", "Gecko skin", "Blattaria", "Empty",
                             "Ramphotyphlops", "Gonatodes antillensis", "Phylodactylus"))
p3 + coord_polar() + ylim(-0.5,1.2)

# Hemidactylus
p4 <- ggplot(hemi, aes(x = Specimen, y = value, fill = as.factor(variable))) +
  geom_bar(stat = "identity",width=1) + theme_set(theme_bw(10)) + 
  scale_fill_manual(values = cols, name = "Prey Category", 
                    breaks=c("Diptera", "Lepidoptera","Coleoptera","Archnid_scorp",
                             "Archnid_spider","Other", "Nematodes", "Centipede", 
                             "Isopod", "Hemiptera", "Hymenoptera", "Orthoptera", 
                             "Ephermeroptera", "Gecko_skin", "Blattaria", "Empty", 
                             "Ramphotyphlops", "Gonatodes antillensis", "Phylodactylus"), 
                    labels=c("Diptera", "Lepidoptera","Coleoptera","Archnid scorpion",
                             "Archnid spider","Other", "Nematodes", "Centipede", 
                             "Isopod", "Hemiptera", "Hymenoptera", "Orthoptera", 
                             "Ephermeroptera", "Gecko skin", "Blattaria", "Empty",
                             "Ramphotyphlops", "Gonatodes antillensis", "Phylodactylus"))
p4 + coord_polar() + ylim(-0.5,1.2)

```

### Diet non-metric multidimensional scaling

```{r}

# Read in data and logic files (file path will need to be updated)
dietsgeckovegan.AL <- read.csv("Hemi MDS R data.csv", header = TRUE) 
dietsgeckologic.AL <- read.csv("Hemi MDS R data logic.csv", header = TRUE) 

# Compute dissimilarity indices and Kruskal's Non-metric Multidimensional Scaling (isoMDS)
gecko.disAL <- vegdist(dietsgeckovegan.AL)
gecko.disAL1 <- gecko.disAL
gecko.disAL1[which(gecko.disAL1==0)] <- 0.000000000000001
gecko.mds0AL <- isoMDS(gecko.disAL1)
stressplot(gecko.mds0AL, gecko.disAL1)
ordiplot(gecko.mds0AL)

# Use wrapper function (metaMDS) for non-metric multidimensional scaling with random start

gecko.mdsAL <-metaMDS(dietsgeckovegan.AL, distance = "bray", k = 2, trymax = 5, autotransform = TRUE, noshare = 0.1, wascores = TRUE, expand = TRUE, trace = 1, plot = FALSE, old.wa = FALSE, zerodist = "add")

gecko.mdsAL

ptsAL <- gecko.mdsAL$points
plot(ptsAL[,1], ptsAL[,2])
spsAL <- gecko.mdsAL$species
plot(spsAL[,1], spsAL[,2])
ord2AL <- cbind(dietsgeckologic.AL, ptsAL)

sps2AL <- data.frame(spsAL)
rownames(sps2AL)[1] <- "Diptera"
rownames(sps2AL)[2] <- "Lepidoptera"
rownames(sps2AL)[3] <- "Coleoptera"
rownames(sps2AL)[4] <- "Archnid_scorp"
rownames(sps2AL)[5] <- "Archnid_spider"
rownames(sps2AL)[6] <- "Other"
rownames(sps2AL)[7] <- "Nematodes"
rownames(sps2AL)[8] <- "Centipede"
rownames(sps2AL)[9] <- "Isopod"
rownames(sps2AL)[10] <- "Hemiptera"
rownames(sps2AL)[11] <- "Hymenoptera"
rownames(sps2AL)[12] <- "Orthoptera"
rownames(sps2AL)[13] <- "Ephermeroptera"
rownames(sps2AL)[14] <- "Gecko_skin"
rownames(sps2AL)[15] <- "Blattaria"
#rownames(sps2AL)[16] <- "Ramphotyphlops"
#rownames(sps2AL)[17] <- "Gonatodes"
#rownames(sps2AL)[18] <- "Phyllodactylus"

colorpal <- brewer.pal(4, "Set1")

x <- ord2AL$MDS1
y <- ord2AL$MDS2
group <- ord2AL$Species
form <- ord2AL$Site2
df <- data.frame(x=x, y=y, group=factor(group))

df_ell <- data.frame() 
for(g in levels(df$group)){df_ell <- rbind(df_ell, cbind(as.data.frame(with(df[df$group==g,], ellipse(cor(x, y),scale=c(sd(x),sd(y)),centre=c(mean(x),mean(y))))),group=g))} 

p1 <- ggplot(data=df, aes(x=x, y=y)) + geom_point(size=4, alpha=0.5, aes(colour=(group))) + 
  geom_path(data=df_ell, aes(x=x, y=y,colour=(group)))+ theme_set(theme_bw(24)) + scale_colour_manual(values=colorpal, name = "Site", 
    breaks=c("Curacao"), labels=c("Curacao")) + scale_shape_manual(values=c(17, 19), name="Species", 
      breaks=c("hemidactylus", "phyllodactylus"), labels=c("Hemidactylus", "Phyllodactylus")) + xlab("Dimension 1") + ylab("Dimension 2")
p1 + geom_text(data=sps2AL, x=sps2AL[,1], y=sps2AL[,2], aes(label=row.names(sps2AL)))

# And now without the sites with overlap
overlap.sites <- c("carmabi", "lagun", "westpunt")
overlaps <- dietsgeckologic.AL$Site %in% overlap.sites
df <- df[overlaps,]

p1 <- ggplot(data=df, aes(x=x, y=y)) + geom_point(size=4, alpha=0.5, aes(colour=(group))) + 
  geom_path(data=df_ell, aes(x=x, y=y,colour=(group)))+ theme_set(theme_bw(24)) + scale_colour_manual(values=colorpal, name = "Site", 
    breaks=c("Curacao"), labels=c("Curacao")) + scale_shape_manual(values=c(17, 19), name="Species", 
      breaks=c("hemidactylus", "phyllodactylus"), labels=c("Hemidactylus", "Phyllodactylus")) + xlab("Dimension 1") + ylab("Dimension 2")
p1 + geom_text(data=sps2AL, x=sps2AL[,1], y=sps2AL[,2], aes(label=row.names(sps2AL)))

```


### Diet NMDS, area of overlap only

```{r}
overlap.sites <- c("carmabi", "lagun", "westpunt")


dietsgeckovegan.DW <- read.csv("Hemi MDS R data.csv", header = TRUE) 
dietsgeckologic.DW <- read.csv("Hemi MDS R data logic.csv", header = TRUE) 

overlaps <- dietsgeckologic.DW$Site %in% overlap.sites
dietsgeckovegan.DW <- dietsgeckovegan.DW[overlaps,]
dietsgeckologic.DW <- dietsgeckologic.DW[overlaps,]

# Compute dissimilarity indices and Kruskal's Non-metric Multidimensional Scaling (isoMDS)
gecko.disDW <- vegdist(dietsgeckovegan.DW)
gecko.disDW1 <- gecko.disDW
gecko.disDW1[which(gecko.disDW1==0)] <- 0.000000000000001
gecko.mds0DW <- isoMDS(gecko.disDW1)
stressplot(gecko.mds0DW, gecko.disDW1)
ordiplot(gecko.mds0DW)

# Use wrapper function (metaMDS) for non-metric multidimensional scaling with random start

gecko.mdsDW <-metaMDS(dietsgeckovegan.DW, distance = "bray", k = 2, trymax = 5, autotransform = TRUE, noshare = 0.1, wascores = TRUE, expand = TRUE, trace = 1, plot = FALSE, old.wa = FALSE, zerodist = "add")

gecko.mdsDW

ptsDW <- gecko.mdsDW$points
plot(ptsDW[,1], ptsDW[,2])
spsDW <- gecko.mdsDW$species
plot(spsDW[,1], spsDW[,2])
ord2DW <- cbind(dietsgeckologic.DW, ptsDW)

sps2DW <- data.frame(spsDW)
rownames(sps2DW)[1] <- "Diptera"
rownames(sps2DW)[2] <- "Lepidoptera"
rownames(sps2DW)[3] <- "Coleoptera"
rownames(sps2DW)[4] <- "Archnid_scorp"
rownames(sps2DW)[5] <- "Archnid_spider"
rownames(sps2DW)[6] <- "Other"
rownames(sps2DW)[7] <- "Nematodes"
rownames(sps2DW)[8] <- "Centipede"
rownames(sps2DW)[9] <- "Isopod"
rownames(sps2DW)[10] <- "Hemiptera"
rownames(sps2DW)[11] <- "Hymenoptera"
rownames(sps2DW)[12] <- "Orthoptera"
rownames(sps2DW)[13] <- "Ephermeroptera"
rownames(sps2DW)[14] <- "Gecko_skin"
rownames(sps2DW)[15] <- "Blattaria"
#rownames(sps2DW)[16] <- "Ramphotyphlops"
#rownames(sps2DW)[17] <- "Gonatodes"
#rownames(sps2DW)[18] <- "Phyllodactylus"

colorpal <- brewer.pal(4, "Set1")

x <- ord2DW$MDS1
y <- ord2DW$MDS2
group <- ord2DW$Species
form <- ord2DW$Site2
df <- data.frame(x=x, y=y, group=factor(group))


df_ell <- data.frame() 
for(g in levels(df$group)){df_ell <- rbind(df_ell, cbind(as.data.frame(with(df[df$group==g,], ellipse(cor(x, y),scale=c(sd(x),sd(y)),centre=c(mean(x),mean(y))))),group=g))} 

p1 <- ggplot(data=df, aes(x=x, y=y)) + geom_point(size=4, alpha=0.5, aes(colour=(group))) + 
  geom_path(data=df_ell, aes(x=x, y=y,colour=(group)))+ theme_set(theme_bw(24)) + scale_colour_manual(values=colorpal, name = "Site", 
    breaks=c("Curacao"), labels=c("Curacao")) + scale_shape_manual(values=c(17, 19), name="Species", 
      breaks=c("hemidactylus", "phyllodactylus"), labels=c("Hemidactylus", "Phyllodactylus")) + xlab("Dimension 1") + ylab("Dimension 2")
p1 + geom_text(data=sps2DW, x=sps2DW[,1], y=sps2DW[,2], aes(label=row.names(sps2DW)))


```

### T-test to show differences in parasites between species

```{r}

parasites <- read.csv("Parasites.csv", header = TRUE)
t.test(Nematodes~Species, data=parasites)

```
